### ISSUE TITLE
about permissions

### ISSUE THREAD

**Issue by ippaveln** [vrtmrz/filesystem-livesync#10]
Hello!

Thanks for your project.

Question: if you run it from Docker, then the files and folders will have the owner "root", but if you specify docker --user "$(id -u):$(id -g)", then the container will not start. I would like to have access to files on behalf of the user. How did you solve this issue?

**Comment by vrtmrz** [comment]
Thank you for asking me!
I am preparing the new edition of this, however, the same problem might happen.
If you have run it once in the root, have you changed the permissions of files which have already been made? 
I hope that changing the permission will help us...

**Comment by ippaveln** [comment]
Thanks for your reply!

Yes, your suggestion worked. Thank you.
