### ISSUE TITLE
Does not sync existing vault content

### ISSUE THREAD

**Issue by heywoodlh** [vrtmrz/filesystem-livesync#2]
The program doesn't seem to pull down existing files/folders in the vault. The [README.md in the Dockerfile pull request](https://github.com/vrtmrz/filesystem-livesync/pull/1) pretty much sums up how I ran the application.

**Comment by vrtmrz** [comment]
Yes! currently, it lacks that feature! Deleting folders is also not enough.
I'll make them in a while! 

And thank you for your pull request!

**Comment by heywoodlh** [comment]
Feel free to tell me this is a different issue but I assume it's the same.

Deleting files from the filesystem doesn't delete it on other devices. However, deleting the file in Obsidian the watcher does delete it. It seems just deleting it in the filesystem the Watcher ignores it.

**Comment by vrtmrz** [comment]
Sorry for being late!

In the case of initial scan is designed behavior. If the files were deleted while filesystem-livesync is running, it should be detected.
Doesn't works fine?

**Comment by heywoodlh** [comment]
Yeah, it works just fine once I added the configuration to sync, which is why I closed it.

**Comment by vrtmrz** [comment]
That’s good! I'm so relieved.
Thank you again!
