### ISSUE TITLE
Files named 'undefined'

### ISSUE THREAD

**Issue by heywoodlh** [vrtmrz/filesystem-livesync#3]
Creating a file this way:

```
echo 'blah' > /data/Study/test.md
```

Results in this output:

```
4/15/2022, 5:25:45 PM->Detected:change:/data/Study/test.md
4/15/2022, 5:25:45 PM->note content saven, pieces:1 new:1, skip:0, cache:0
4/15/2022, 5:25:45 PM->note saved:undefinedtest.md:5-da2350c3acc24b91a0ae10df3a47b737
```

Which creates a file in my vault named `undefinedtest.md`.

This is my config for my vault:

```
    "config_2": {
        "server": {
            "uri": "http://obsidian.kube/obsidian-study",
            "auth": {
                "username": "obsidian",
                "password": "..."
            }
        },
        "local": {
            "path": "/data/Study",
            "--processor": "utils/build.sh",
            "initialScan": false
        },
        "auto_reconnect": true
    }
```

I don't have `utils/build.sh` anywhere. Where should I get that file? And could that be the reason the file isn't getting processed correct?

**Comment by vrtmrz** [comment]
Oh! I forgot the empty configuration treatment. Thank you for pointing out this!

Fixed at this commit.
[b2ce4593b9f2dfeb9352fe8434bf0db8e5f7ec91](https://github.com/vrtmrz/filesystem-livesync/commit/b2ce4593b9f2dfeb9352fe8434bf0db8e5f7ec91)

`build.sh` is just a sample. I'm testing this feature running `rsync` and [Hugo](https://gohugo.io/).

**Comment by heywoodlh** [comment]
Can confirm this fixes it! Thanks!
