### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by hilsonp** [vrtmrz/filesystem-livesync#7]
Hello,

This is not an issue but rather a question.

I'm using obsidian-livesync on 3 devices (2 win10 laptops and on iOS).
My obsidian-livesync-server is running as a docker on my Synology.

I also own a scanner (Brother ADS-2400N) that can write files on a share on that Synology.
I would like to dedicate one physical button of that scanner to send the resulting PDF into my Obsidian Inbox.

If I understand well, I could use filesystem-livesync in order to sync a folder on the synology with my obsidian vault.
I would then have the scanner write new files in the Inbox subfolder of that synology folder and filesystem-livesync would push those new files into my vault.

Is that correct ?

Is this service still on the bleeding edge or are you confident ?

Would you think of a simpliest method of pushing pdf files from my scanner to the obsidian vault (without starting my laptop ;-) ) ?
Pushing pdf files through  a REST API would also be an option as I may create a process handling the pdf produced by the scanner, doing OCR, smart renaming and uploading it to the right folder based on some baysian rules.

Thank you,

Pierre.

**Comment by vrtmrz** [comment]
> Is that correct ?

Yes, this is one of the use cases, especially do not want to take care of watching the file system and checking the differences.
(This is even able to be run if the storage and job-runner is a different machine.)

This app is on the bleeding edge. However, in most cases, we might not lose the files thanks to CouchDB and LiveSync history, substantially. And, we can back it up.
This is why this app stores and exports files in once reflected in the storage.

**Comment by vrtmrz** [comment]
Sorry, I sent it on the way.
> Pushing pdf files through a REST API would also be an option as I may create a process handling the pdf produced by the scanner, doing OCR, smart renaming and uploading it to the right folder based on some baysian rules.

Just in case, the closest solution is [ObsidianReceiver](https://github.com/arminus/ObsidianReceiver).

**Comment by hilsonp** [comment]
Thank you for your reply.

I'll give it a try.

I will probably end up using self-hosted paperless-ngx to ingest, ocr, autorename and move files in subdirectories of one 'resource' directory directory placed in my vault.

In obidian, I would not manage/move those files but would link to them from notes.

This will give me the best of both excellent apps.

I'll let you know ;-)
